### ISSUE TITLE
User model

### ISSUE THREAD

**Issue by EmirVatric** [multiverse-students/Multiverse#11]
Hi ppl,
In this issue, lets try to create a User model, controller, routes and write some unit tests.
User should have => first name, last name, bio, email, password. Don't worry about profile pic we will add that later on, let's get basics going.

IF THERE IS SOMETHING ELSE YOU THINK SHOULD BE ADDED FEEL FREE TO COMMENT.

**Comment by mapra99** [comment]
Hey @EmirVatric! For authentication is it planned to use Devise?

**Comment by EmirVatric** [comment]
@mapra99 go for it :) I would prefer not to use Devise, it generates a lot of unnecessary code and working with it is a little bit more difficult for beginners.
