### ISSUE TITLE
post controller

### ISSUE THREAD

**Issue by EmirVatric** [multiverse-students/Multiverse#17]
Refactor the post controller to return json for the frontend.

**Comment by gr1d99** [comment]
Hi, I think this will be a good start for me, I have been working with API only backed apps for a while but I a sure I will be able to handle this.

**Comment by EmirVatric** [comment]
Hi @gr1d99 welcome :) Go for it 👍

**Comment by gr1d99** [comment]
Thanks @EmirVatric

**Comment by gr1d99** [comment]
Hey @EmirVatric, correct me if I am wrong

These are the actions that should respond with JSON data right?

- [ ] create
- [ ] show
- [ ] update
- [ ] delete
